# Generated by Django 2.2.1 on 2019-07-31 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_performer_performer_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='name2',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
