# Generated by Django 2.2.1 on 2019-07-31 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_product_name2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='name2',
        ),
    ]
